language: node_js
node_js:
  - node
addons:
  sonarcloud:
    organization: "$ORG_KEY"
    token:
      secure: "$SONAR_TOKEN"
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  region: eu-central-1
  skip_cleanup: false
  local_dir: static
  on:
    branch: master